magic8ball = """
             ZZOOO88DDNNMM              
         7$7$$ZZZOO88DNNNMMMM+          
       Z7II777$$ZZO88DDNNMMMMMMM        
     ,77?::+77$$ZOOO8DDNNMMMMMMMM       
    $$$7I=+I77$$ZOO88DDNNMMMMMMMMMM     
   OZ$$777777$$ZZOO88DDNNMMMMMMMMMMM    
 .OOZZ$$$$$$$$ZMMMMONMMMMMMMMMMMMMMMM   
 N8OOZZZZZ$ZZMD         +MMMMMMMMMMMM$  
 D888OOOOOOOM             ZMMMMMMMMMMM  
=DD8888O8OOM    I8DD888    $MMMMMMMMMM  
NNNDDD8888M     N     D.    $MMMMMMMMMM 
MNNNNNNDDDM     N    .D,    OMMMMMMMMMM 
MMMMMNNNNNM     8MDDDDN.    ZMMMMMMMMMM 
MMMMMMMMMMM     M     M,    +MMMMMMMMMM 
 MMMMMMMMMMD    M     M,   ,MMMMMMMMMM. 
 MMMMMMMMMMMZ   .~~~~~.   .MMMMMMMMMMM. 
 ZMMMMMMMMMMMO.          ~MMMMMMMMMMM.  
 .MMMMMMMMMMMMMD7~   ,=8MMMMMMMMMMMMM   
   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
   .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM     
      MMMMMMMMMMMMMMMMMMMMMMMMMMM       
       IMMMMMMMMMMMMMMMMMMMMMMM=        
          MMMMMMMMMMMMMMMMMMM           
             MMMMMMMMMMMMM.                                                                                       
"""
print(magic8ball)
input("Press Enter to Exit")

